server:
  port: 3001

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order, /order/**

        - id: order-handler
          uri: lb://order-handler
          predicates:
            - Path=/orderHandler/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**, /category, /category/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wx7ne78bg2ztxwxc.us.auth0.com/
          client-id: 8mfLvSWBhTSqpXuYEOBH3GyELMTymqmn
          client-secret: OJEA71P8KwhylsYP7eM5a5WyUK5nqIPvC9j3Mor3N8MeHFJ-Qff11tSjmXI7K9pB
          audience: auth0-spring

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:3000/eureka/

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.auth0.example: DEBUG
#    com.netflix.discovery: DEBUG
